#!/bin/sh

filename=$1
noext="${filename%.*}"
rm -f "output.txt"
time rm -f $noext
time /usr/local/bin/g++-9 -g -O3 -std=gnu++17 -Wfatal-errors -Wall -Wextra -Wconversion -pedantic -Wshadow -DLOCAL -o $noext $1 -I$2
